class Dialogobject(object):

    def Dialogmanger():
        intent,entity=watson.watsonspeech()
        print(intent)
        #print(intent)
        key=1
        door=0
        hammer=0
        greetingvar=0
        if(intent=="possession"):
            if(entity=="key"):
                if(key==0):
                    key=1
                    action="pk"
                    Fas.Possesion(action)
                elif(key==1):
                    action="pka"
                    Fas.Possesion(action)
            elif(entity=="hammer"):
                if(hammer==0):
                    hammer=1
                    action="ph"
                    Fas.Possesion(action)
                elif(hammer==1):
                    action="pha"
                    Fas.Possesion(action)
            elif(entity=="empty"):
                action="pui"
                Fas.Possesion(action)

        elif(intent=="release"):
            if(entity=="key"):
                if(key==1):
                    key=0
                    action="rk"
                    Fas.Release(action)
                elif(key==0):
                    action="rka"
                    Fas.Release(action)
            elif(entity=="hammer"):
                if(hammer==1):
                    hammer=0
                    action="rh"
                    Fas.Release(action)
                elif(hammer==0):
                    action="rha"
                    Fas.Release(action)
            elif(entity=="empty"):
                action="rui"
                Fas.Release(action)
            else:
                action="rui"
                Fas.Release(action)

        elif(intent=="unlock"):
            if(entity=="door"):
                if(door==0):
                    if(key==1):
                        door=1
                        action="ud"
                        Fas.Unlock(action)
                    elif(key==0):
                        action="udnk"
                        Fas.Unlock(action)
                elif(door==1):
                    action="dao"
                    Fas.Unlock(action)
            elif(enitiy=="empty"):
                action="dui"
                Fas.Unlock(action)

        elif(intent=="break"):
            if(entity=="door"):
                if(door==0):
                    if(hammer==1):
                        door=1
                        action="bd"
                        Fas.Break(action)
                    elif(hammer==0):
                        action="bdnk"
                        Fas.Break(action)
                elif(door==1):
                    action="dab"
                    Fas.Break(action)
            elif(entity=="empty"):
                action="dui"
                Fas.Break(action)
        elif(intent=="undefined"):
            action="ud"
            Fas.undefined(action)
        elif(intent=="greeting"):
            if(greetingvar==0):
                greetingvar=1
                action="gf"
                Fas.Greeting(action)
            elif(greetingvar==1):
                action="ga"
                Fas.Greeting(action)
        elif(intent=="goodbye"):
            action="gb"
            Fas.Goodbye(action)
