list_Possesion=['use the key,pick up the key','grab the key','take the key','get the key','obtain the key','pick up the hammer','use the hammer','grab the hammer','get the hammer','pick the hammer','obtain the hammer','pick up the sword','pick up the sword from the rock','take the sword','grab the sword','take the blade']
list_break=['break the wall','samash the wall','destro the wall']
list_kill=['kill the dragon','kill the beast','kill the animal','kill the creature','attack the dragon','fight the dragon','kill the monster','fight the beast','attack the monster','attack the beast']
list_open=['open the treasure','open the chest','open the box','get the box','open the chest with key','unlock the treasure chest']
list_release=['drop the hammer','drop the key','relese the key','release the hammer']
